### ISSUE TITLE
Not work for swift 3

### ISSUE THREAD

**Issue by young310** [AprilBrother/iOS-ASensor-demo#1]
Hi,

When I use Xcode 8.3.3, it is forced to upgrade the source code to swift 3.
There are errors, such as the NSMakeRange conversion problem. 

I am new to swift 3, but can do well using objective-c. Any suggestion?

<img width="1512" alt="2017-07-10 17 46 09" src="https://user-images.githubusercontent.com/8056293/28012206-ac3855e4-6597-11e7-8f9f-5669137940fa.png">

**Comment by daisysomus** [comment]
Swift 3 has many changes, so you should migrate to swift 3. it's apple , you know.
