### ISSUE TITLE
Mac address is different every time

### ISSUE THREAD

**Issue by Haridasan** [AprilBrother/iOS-ASensor-demo#2]
Hi April,
 First of all thanks for your code reference, as I learnt how to get the advertisement data for a BLE 
 device.
 But the issue is it is showing different mac address for a same device every time I scan which is 
 incorrect. Please explain this issue and I'm waiting for your reply.

**Comment by volca** [comment]
How do you scan the BLE advertising data and parse the MAC address?

**Comment by Haridasan** [comment]
I followed the same way in your code like this :
func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral, advertisementData: [String : Any], rssi RSSI: NSNumber){
if let data = advertisementData["kCBAdvDataManufacturerData"] as? NSData{
                let macAddressData: NSData = data.subdata(with: NSMakeRange(2, 6)) as NSData
                let macAddressString = String(macAddressData.hexadecimalString)
                print("macaddress = \(macAddressString)")
 }
}

**Comment by volca** [comment]
You should also detect the advertising data length. Not all kCBAdvDataManufacturerData are the sensor data. 

Which model sensor did you buy? ABSensor DH or other?
